# Generated by Django 4.1.2 on 2022-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["id"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="prev_id",
            field=models.IntegerField(null=True),
        ),
    ]
