# Generated by Django 4.1.2 on 2022-10-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_options_reservation_prev_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="prev_id",
        ),
    ]
